In [1]:
import pandas as pd 
alunos = {'Nome':['Guilherme','Amanda','Pedro','Carlos','Bianca'],
         'Nota':[4,6.5,7,8,3.5],
          'Aprovado':['Nao','Sim','Sim','Sim','Nao',]
         }

In [3]:
dataFrame = pd.DataFrame(alunos)

In [7]:
print(dataFrame)

        Nome  Nota Aprovado
0  Guilherme   4.0      Nao
1     Amanda   6.5      Sim
2      Pedro   7.0      Sim
3     Carlos   8.0      Sim
4     Bianca   3.5      Nao


In [9]:
objeto = pd.Series([2,6,3,7,8])
print(objeto)

0    2
1    6
2    3
3    7
4    8
dtype: int64


In [19]:
import numpy as np

#Array uni dimensional 
array1 = np.array([2,6,3,7,8])
print(array1)

#Array de deuas dimensoes
array2 = np.array([(2,6,3,7,8),(2,6,3,7,8)])
print(array2)

[2 6 3 7 8]
[[2 6 3 7 8]
 [2 6 3 7 8]]


In [23]:
objeto2 = pd.Series(array1)

print(objeto2)



0    2
1    6
2    3
3    7
4    8
dtype: int32
